```{r, echo=FALSE, warning=FALSE, cache=FALSE}
library(ggplot2)
suppressMessages(library(dplyr))

options(warn=-1)

#change this location to your own server log
serverlog <- ""

#add the IP of your dev environment so you aren't counting yourself
regular.ips <- c()

raw <- read.table(serverlog) %>%
  select(ip = V1, datetime = V4, request = V6,
         http.code = V7, size = V8, referrer = V9,
         browser.os = V10) %>%
  mutate(datetime = as.Date(datetime, format="[%d/%b/%Y:%H:%M:%S"))

#Assume any HTTP code 200 is a visit, ignore all others
keep <- 
  raw %>%
  subset(http.code >= 200 & http.code <= 299 &
              datetime >= Sys.Date() - 7 &
              referrer != "-")

keep$basename <- sapply(keep$referrer, function(x) httr::parse_url(x)$hostname)
unique.lookup <- data.frame(ip=unique(keep$ip))

roughjson <- 
  unique.lookup %>%
  group_by("ip") %>%
  do(data.frame(result = RCurl::getURL(paste0("ipinfo.io/", .$ip))))
                              
expandedjson <- c()
for(x in roughjson$result){
  json_file <- RJSONIO::fromJSON(x)

  json_file[sapply(json_file, is.null)] <- NA
  json_file <- unlist(json_file)

  expandedjson <- rbind(expandedjson, json_file[c("ip", "city", "country", "hostname", "org")])
  }

expandedjson <- merge(expandedjson, keep)

expandedjson[] <- lapply(expandedjson, as.character)
expandedjson <- expandedjson[!(expandedjson$ip %in% regular.ips), ]

forplot <- 
  expandedjson %>%
  select(ip, datetime, city, country, basename, org) %>%
  distinct %>%
  filter(complete.cases(city)) %>%
  mutate(city.country = paste(city, country, sep=","))
forplot$basename[sapply(forplot$basename, is.null)] <- NA
```

Generation Data
```{r}
print(paste("Figures generated at", Sys.time(), sep=" "))
```

```{r fig.width=9, fig.height=13, echo=FALSE, warning=FALSE, cache=TRUE}
ggplot(forplot, aes(datetime)) + geom_bar(aes(fill=basename)) + ggtitle("Referrer data")

ggplot(forplot, aes(city.country)) + geom_bar(aes(fill=city.country)) + 
  theme(axis.text.x=element_text(angle = -45, hjust = 0)) +
  ggtitle("Visitor Location data")

ggplot(forplot, aes(org)) + geom_bar(aes(fill=org)) + 
  theme(axis.text.x=element_text(angle = -45, hjust = 0)) +
  ggtitle("Visitor org. data")
```

Seattle specific
```{r, echo=FALSE}
seattle.only <-
  expandedjson %>%
  subset(city %in% c("Redmond", "Seattle")) %>%
  select(ip, hostname, org, datetime) %>%
  distinct
knitr::kable(seattle.only)
```

